"""Crumby data models."""

from . import db

class Crumb(db.Model):
    """Record for crumbs table."""
    __tablename__ = 'crumbs'
    id = db.Column(db.Integer, primary_key=True)
    ip = db.Column(db.String(39))
    cid = db.Column(db.String(10))
    datetime = db.Column(db.DateTime)
    doc_title = db.Column(db.Text)
    doc_uri = db.Column(db.Text)
    doc_enc = db.Column(db.String(25))
    referrer = db.Column(db.Text)
    _referrer = db.Column(db.Text)
    platform = db.Column(db.String(25))
    browser = db.Column(db.String(25))
    version = db.Column(db.String(25))
    screen_res = db.Column(db.String(25))
    screen_depth = db.Column(db.String(10))
    continent = db.Column(db.String(3))
    country = db.Column(db.String(3))
    subdivision_1 = db.Column(db.String(75))
    subdivision_2 = db.Column(db.String(75))
    city = db.Column(db.String(75))
    latitude = db.Column(db.Float)
    longitude = db.Column(db.Float)
    accuracy_radius = db.Column(db.Integer)
    time_zone = db.Column(db.String(50))
    lang = db.Column(db.String(10))
    _lang = db.Column(db.String(10))

    def __init__(self, data):
        self.ip = data.get('ip')
        self.cid = data.get('cid')
        self.datetime = data.get('datetime')
        self.doc_title = data.get('doc_title')
        self.doc_uri = data.get('doc_uri')
        self.doc_enc = data.get('doc_enc')
        self.referrer = data.get('referrer')
        self._referrer = data.get('_referrer')
        self.platform = data.get('platform')
        self.browser = data.get('browser')
        self.version = data.get('version')
        self.screen_res = data.get('screen_res')
        self.screen_depth = data.get('screen_depth')
        self.continent = data.get('continent')
        self.country = data.get('country')
        self.subdivision_1 = data.get('subdivision_1')
        self.subdivision_2 = data.get('subdivision_2')
        self.city = data.get('city')
        self.latitude = data.get('latitude')
        self.longitude = data.get('longitude')
        self.accuracy_radius = data.get('accuracy_radius')
        self.time_zone = data.get('time_zone')
        self.lang = data.get('lang')
        self._lang = data.get('_lang')
