#!/bin/sh

cd $OPENSHIFT_DATA_DIR

# create secret key
touch key
cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1 | key

# obtain geolite db
rm -f GeoLite2-City.mmdb.gz
rm -f GeoLite2-City.md5

if [ ! -e "GeoLite2-City.mmdb" ] || [ $(find GeoLite2-City.mmdb -mtime +30) ]; then

  rm -f GeoLite2-City.mmdb

  wget http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz
  wget http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.md5

  gzip -d GeoLite2-City.mmdb.gz

  file1=($(md5sum GeoLite2-City.mmdb))
  file2=$(cat GeoLite2-City.md5)

  if [ "$file1" = "$file2" ]; then
    echo "Downloaded GeoLite2-City DB to $OPENSHIFT_DATA_DIR"
  else
    echo "WARN: GeoLite2-City DB MD5 check failed!"
  fi

else

  echo "Current GeoLite2-City DB <30 days"

fi
